sudo: required
language: generic


services:
  - docker


before_install:
  - docker build -t zhifanli/docker-ci-cd -f Dockerfile.dev .




script:
  - docker run -e CI=true zhifanli/docker-ci-cd npm run test


deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-ci-cd"
  env: "Dockercicd-env"
  bucket_name: "elasticbeanstalk-ca-central-1-862931123853"
  bucket_path: "docker-ci-cd"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
